"""Monitoring add-on: Prometheus + Grafana with Rocket.Chat metrics.

Layered onto ANY repro (via `up --monitor` at creation, or `rc-repro monitor`
to attach to a running one) rather than being its own preset — monitoring is
cross-cutting, and Prometheus must scrape whatever RC topology exists (a single
`rocketchat`, or `rocketchat-1..N` for multi-instance). The scrape targets are
generated from the actual RC service names.

Config mirrors the official RocketChat/rocketchat-compose (compose.monitoring.yml
+ files/): Prometheus with file-based service discovery, Grafana provisioned with
a Prometheus datasource and the official "Rocket.Chat Metrics" dashboard (shipped
in data/monitoring/).
"""

from __future__ import annotations

from importlib import resources

from rc_repro import config

# Service + volume names, so attach/detach can find and remove them.
SERVICES = ("prometheus", "grafana", "node-exporter", "mongodb-exporter")
VOLUMES = ("prometheus_tsdb", "grafana_data")

# RC setting that opens the /metrics endpoint on :9458 — used both as an API
# setting id (attach, live toggle) and as the OVERWRITE_SETTING env (up --monitor).
RC_METRICS_SETTING = "Prometheus_Enabled"
RC_METRICS_ENV = "OVERWRITE_SETTING_" + RC_METRICS_SETTING

_PROM_PORT, _GRAFANA_PORT = config.MONITOR_PORTS

# Pinned to the official compose.monitoring.yml defaults (multi-arch).
_PROMETHEUS_IMAGE = "docker.io/prom/prometheus:v3.4.2"
_GRAFANA_IMAGE = "docker.io/grafana/grafana:12.0.2"
_NODE_EXPORTER_IMAGE = "docker.io/prom/node-exporter:v1.9.1"
_MONGODB_EXPORTER_IMAGE = "docker.io/percona/mongodb_exporter:0.43.1"

_PROMETHEUS_YML = """\
# Generated by rc-repro (mirrors RocketChat/rocketchat-compose).
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: file_sd_configs
    file_sd_configs:
      - refresh_interval: 15s
        files:
          - /etc/prometheus/file_sd_configs/*.yml
"""

_DATASOURCE_YML = """\
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    uid: DS_PROMETHEUS
"""

_DASHBOARDS_YML = """\
apiVersion: 1
providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: true
    updateIntervalSeconds: 30
    allowUiUpdates: false
    options:
      path: /dashboards
      foldersFromFilesStructure: true
"""


def _sd(targets: list[str], job: str) -> str:
    """A Prometheus file-SD target block."""
    lines = [f"# Generated by rc-repro. Prometheus scrape targets ({job}).", "- targets:"]
    lines += [f"    - {t}" for t in targets]
    lines += ["  labels:", f"    job: {job}", f"    service: {job}"]
    return "\n".join(lines) + "\n"


def services() -> dict:
    """The prometheus + grafana compose services with BARE host:container ports.
    The caller binds them to the host interface (compose._bind_ports for
    `up --monitor`, or the attach path directly) so they're never double-bound."""
    return {
        "prometheus": {
            "image": _PROMETHEUS_IMAGE,
            "command": [
                "--config.file=/etc/prometheus/prometheus.yml",
                "--web.enable-lifecycle",
                "--storage.tsdb.retention.time=15d",
                # Accept pushed metrics: loadtest --live streams k6 results here,
                # so client-side load sits next to RC metrics in Grafana.
                "--web.enable-remote-write-receiver",
            ],
            "volumes": [
                "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro",
                "./monitoring/file_sd_configs:/etc/prometheus/file_sd_configs:ro",
                "prometheus_tsdb:/prometheus",
            ],
            "ports": [f"{_PROM_PORT}:9090"],
            "restart": "unless-stopped",
        },
        "grafana": {
            "image": _GRAFANA_IMAGE,
            "environment": {
                "GF_SECURITY_ADMIN_USER": "admin",
                "GF_SECURITY_ADMIN_PASSWORD": "admin",
                # Anonymous read access so the dashboard opens with no login (local repro).
                "GF_AUTH_ANONYMOUS_ENABLED": "true",
                "GF_AUTH_ANONYMOUS_ORG_ROLE": "Viewer",
            },
            "volumes": [
                "./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro",
                "./monitoring/grafana/dashboards:/dashboards:ro",
                "grafana_data:/var/lib/grafana",
            ],
            "ports": [f"{_GRAFANA_PORT}:3000"],
            "depends_on": ["prometheus"],
            "restart": "unless-stopped",
        },
        # Host/OS metrics. The official compose runs this in host-network mode
        # (Linux); rc-repro uses the compose network so Prometheus scrapes it at
        # node-exporter:9100 portably on Mac/Windows/Linux (metrics reflect the
        # Docker VM there rather than the bare host — fine for a local repro).
        "node-exporter": {
            "image": _NODE_EXPORTER_IMAGE,
            "command": [
                "--path.procfs=/host/proc",
                "--path.sysfs=/host/sys",
                "--path.rootfs=/rootfs",
                "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)",
            ],
            "volumes": ["/proc:/host/proc:ro", "/sys:/host/sys:ro", "/:/rootfs:ro"],
            "restart": "unless-stopped",
        },
        # MongoDB metrics. No auth in rc-repro's Mongo (ALLOW_EMPTY_PASSWORD),
        # so a plain URI works; directConnection reaches the single RS node.
        "mongodb-exporter": {
            "image": _MONGODB_EXPORTER_IMAGE,
            "command": [
                "--mongodb.uri=mongodb://mongodb:27017/?directConnection=true",
                "--collect-all",
                "--compatible-mode",
            ],
            "depends_on": ["mongodb"],
            "restart": "unless-stopped",
        },
    }


def bind_ports(svcs: dict, bind_host: str) -> dict:
    """Prefix each service's published ports with `bind_host`. Services with no
    published ports (the exporters) are left untouched. Used by the attach path
    (`up --monitor` binds via compose._bind_ports instead)."""
    for svc in svcs.values():
        if bind_host and svc.get("ports"):
            svc["ports"] = [f"{bind_host}:{p}" for p in svc["ports"]]
    return svcs


def volumes() -> dict:
    return {v: {"driver": "local"} for v in VOLUMES}


def _dashboard(name: str) -> str:
    return resources.files("rc_repro").joinpath("data", "monitoring", name).read_text(encoding="utf-8")


def files(rc_services: list[str]) -> list[tuple[str, str]]:
    """Config files written into the repro workspace (mounted by the services).
    Prometheus scrapes RC (all instances), MongoDB, and the host via file-SD."""
    return [
        ("monitoring/prometheus.yml", _PROMETHEUS_YML),
        ("monitoring/file_sd_configs/rocketchat.yml",
         _sd([f"{s}:9458" for s in rc_services], "rocketchat")),
        ("monitoring/file_sd_configs/mongo.yml", _sd(["mongodb-exporter:9216"], "mongodb")),
        ("monitoring/file_sd_configs/node-exporter.yml", _sd(["node-exporter:9100"], "node-exporter")),
        ("monitoring/grafana/provisioning/datasources/prometheus.yml", _DATASOURCE_YML),
        ("monitoring/grafana/provisioning/dashboards/from-dir.yml", _DASHBOARDS_YML),
        ("monitoring/grafana/dashboards/rocketchat-metrics.json", _dashboard("rocketchat-metrics.json")),
        ("monitoring/grafana/dashboards/node-exporter-full.json", _dashboard("node-exporter-full.json")),
        ("monitoring/grafana/dashboards/mongodb-exporter.json", _dashboard("mongodb-exporter.json")),
        # Client-side load metrics streamed by `loadtest --live` (remote-write).
        ("monitoring/grafana/dashboards/k6-loadtest.json", _dashboard("k6-loadtest.json")),
    ]


def notes() -> list[str]:
    return [
        f"Grafana:    http://localhost:{_GRAFANA_PORT}  (admin/admin; anonymous view enabled)",
        f"Prometheus: http://localhost:{_PROM_PORT}  (Status -> Targets: rocketchat, mongodb, node-exporter)",
        "Dashboards auto-provisioned: Rocket.Chat Metrics, MongoDB, Node Exporter Full.",
        "k6 Load Test dashboard is provisioned too; it fills in while a "
        "`loadtest --live` run streams metrics.",
    ]
