"""Dynamic `multi-instance` preset: N Rocket.Chat instances behind Traefik,
sharing one MongoDB replica set and coordinating over NATS.

Reproduces horizontal-scaling tickets — cross-instance real-time, presence, and
sticky-session / websocket issues. Modelled on the official
RocketChat/rocketchat-compose (compose.nats.yml + compose.traefik.yml):

  * Instances talk to each other over NATS (the moleculer transporter), so the
    legacy INSTANCE_IP DDP mesh isn't used.
  * Traefik load-balances via its FILE provider — a `dynamic.yml` listing the
    backend instances. Upstream generates that file from ROCKETCHAT_BACKEND_SERVERS
    with an init container; we know the instance count at build time, so we
    generate it directly here (no init container, no Docker-socket dependency).

The heavy lifting (cloning rocketchat into rocketchat-1..N, wiring the NATS
transporter, handing Traefik the published host port) happens in compose.build,
because the RC image, env and host port aren't known until `up`.

Parameters (via `--set`):
  instances   number of Rocket.Chat instances to run (default 2, clamped 2..5).
"""

from __future__ import annotations

from rc_repro.presets import Preset

# Pinned to match the official rocketchat-compose defaults (both multi-arch;
# verify with `docker manifest inspect` before release, as with the Mongo images).
_NATS_TAG = "2.11-alpine"
_TRAEFIK_TAG = "v3.4"


def _dynamic_config(n: int) -> str:
    """Traefik file-provider config: one load-balancer service fronting the N
    instances, with a sticky cookie so a client's websocket (DDP) stays pinned
    to one instance instead of being bounced mid-session."""
    servers = "\n".join(
        f'          - url: "http://rocketchat-{i}:3000"' for i in range(1, n + 1)
    )
    return (
        "# Generated by rc-repro. Do not edit by hand -- re-run `rc-repro up`.\n"
        "# Traefik file provider: load-balance across the rocketchat-1..N instances.\n"
        "http:\n"
        "  routers:\n"
        "    rocketchat:\n"
        '      rule: "PathPrefix(`/`)"\n'
        "      entryPoints: [web]\n"
        "      service: rocketchat\n"
        "  services:\n"
        "    rocketchat:\n"
        "      loadBalancer:\n"
        "        healthCheck:\n"           # only route to instances serving /api/info
        "          path: /api/info\n"
        '          interval: "10s"\n'
        '          timeout: "5s"\n'
        "        sticky:\n"
        "          cookie:\n"
        "            name: rc_lb\n"
        "        servers:\n"
        f"{servers}\n"
    )


def build(params: dict) -> Preset:
    instances = max(2, min(5, int(params.get("instances", 2) or 2)))

    services = {
        # Inter-instance message broker (presence, notifications, streaming).
        "nats": {
            "image": f"docker.io/nats:{_NATS_TAG}",
            "restart": "unless-stopped",
            "command": ["--http_port", "8222"],
        },
        # Reverse proxy / load balancer. File provider reads the generated
        # dynamic.yml (mounted below); compose.build injects the published host
        # port as `<host>:80` via entry_service.
        "traefik": {
            "image": f"docker.io/traefik:{_TRAEFIK_TAG}",
            "restart": "unless-stopped",
            "command": [
                "--providers.file.filename=/etc/traefik/dynamic.yml",
                "--providers.file.watch=true",
                "--entryPoints.web.address=:80",
            ],
            "volumes": ["./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"],
        },
    }

    return Preset(
        name="multi-instance",
        description=(
            f"{instances} Rocket.Chat instances behind Traefik, sharing one Mongo "
            "replica set and NATS. Reproduce horizontal-scaling / real-time-across-"
            "instances tickets."
        ),
        env={},  # per-instance env (TRANSPORTER) is added by compose.build
        services=services,
        depends_on=["nats"],       # every instance also depends on mongo (added by compose)
        instances=instances,       # tells compose.build to clone rocketchat-1..N
        entry_service="traefik",   # tells compose.build to hand the host port to Traefik
        requires_license=False,
        source="built-in (dynamic)",
        files=[("traefik/dynamic.yml", _dynamic_config(instances))],
        params_help={"instances": "number of Rocket.Chat instances (default 2, max 5)"},
        notes=[
            "Verify the mesh (lists every connected instance):",
            "    rc-repro api --name <name> --2fa GET /api/v1/instances.get",
            "Open two different instance URLs (shown above) in separate browsers,",
            "  post in one and watch it arrive in the other (cross-instance real-time).",
        ],
    )
